<?php require_once __DIR__ . '/includes/layout.php';
$all = sort_by_date_desc(json_read('berita'), 'published_at');
$q = trim((string)($_GET['q'] ?? '')); $cat = trim((string)($_GET['cat'] ?? ''));
$categories = ['Berita Resmi','Pembinaan','Kompetisi','Atlet & Pelatih','Opini/Tulisan','Pengumuman'];
$items = array_values(array_filter($all, function($it) use ($q,$cat){
  $text = strtolower(($it['title']??'').' '.($it['excerpt']??'').' '.($it['source_name']??'').' '.($it['category']??''));
  if ($q !== '' && strpos($text, strtolower($q)) === false) return false;
  if ($cat !== '' && strcasecmp((string)($it['category'] ?? 'Berita Resmi'), $cat) !== 0) return false;
  return true;
}));
$featured = $items[0] ?? ($all[0] ?? []);
site_header('Blog & Media Center','berita'); ?>
<section class="module-hero"><div class="container"><span class="eyebrow">Blog & Media Center</span><h1>Artikel, liputan, opini, dan pengumuman resmi PSTI Jawa Timur.</h1><p>Website PSTI Jatim kini juga menjadi blog/media center untuk publikasi berita resmi, pembinaan atlet-pelatih, kompetisi, agenda, dan dokumentasi organisasi.</p></div></section>
<section class="section"><div class="container"><div class="blog-categories"><a class="blog-cat" href="<?= e(base_url('blog.php')) ?>">Semua</a><?php foreach($categories as $c): ?><a class="blog-cat" href="<?= e(base_url('blog.php?cat='.rawurlencode($c))) ?>"><?= e($c) ?></a><?php endforeach; ?></div><div class="blog-shell"><main><?php if($featured): ?><article class="blog-featured"><img src="<?= e(normalize_image($featured['banner'] ?? $featured['image'] ?? 'assets/hero-musprov.jpg')) ?>" alt=""><div class="text"><span class="badge"><?= e((string)($featured['category'] ?? 'Berita Resmi')) ?></span><h2><?= e((string)($featured['title'] ?? 'PSTI Jawa Timur')) ?></h2><p><?= e(mb_strimwidth((string)($featured['excerpt'] ?? 'Media center resmi PSTI Jawa Timur.'),0,220,'...')) ?></p><a class="btn" href="<?= e(base_url('berita-detail.php?id='.(int)($featured['id']??0))) ?>">Baca Artikel</a></div></article><?php endif; ?><div class="blog-list"><?php foreach($items as $it): ?><article class="blog-row"><img src="<?= e(normalize_image($it['banner'] ?? $it['image'] ?? '')) ?>" alt=""><div><span class="badge"><?= e((string)($it['category'] ?? 'Berita Resmi')) ?></span><span class="meta"> · <?= e((string)($it['published_at'] ?? '')) ?></span><h3><?= e((string)($it['title'] ?? 'Artikel')) ?></h3><p><?= e(mb_strimwidth((string)($it['excerpt'] ?? ''),0,180,'...')) ?></p><a class="readmore" href="<?= e(base_url('berita-detail.php?id='.(int)($it['id']??0))) ?>">Baca selengkapnya →</a></div></article><?php endforeach; if(!$items): ?><div class="content">Belum ada artikel untuk filter ini.</div><?php endif; ?></div></main><aside class="blog-sidebar"><div class="sidebar-box"><h3>Cari Artikel</h3><form class="search-box" method="get"><input name="q" value="<?= e($q) ?>" placeholder="Cari berita, atlet, kompetisi..."><button>Cari</button></form></div><div class="sidebar-box"><h3>Kanal Blog</h3><div class="tag-cloud"><?php foreach($categories as $c): ?><span><?= e($c) ?></span><?php endforeach; ?></div></div><div class="sidebar-box"><h3>Arsip Terbaru</h3><?php foreach(array_slice($all,0,5) as $it): ?><p><b><?= e((string)($it['title']??'')) ?></b><br><span class="meta"><?= e((string)($it['published_at']??'')) ?></span></p><?php endforeach; ?></div></aside></div></div></section><?php site_footer(); ?>
