<?php require_once __DIR__ . '/../includes/layout.php'; admin_header('Tutorial & Fungsi Admin', 'tutorial'); ?>
<div class="panel"><h2>Panduan Admin — PSTI Jatim Premium Portal</h2><p class="muted">Website ini dirancang sebagai website resmi, blog/media center, dan sistem informasi organisasi olahraga. Gunakan halaman ini sebagai SOP singkat operator.</p></div>
<div class="stats"><div class="stat"><b>Blog</b><span>Artikel & Berita</span></div><div class="stat"><b>Agenda</b><span>Jadwal Resmi</span></div><div class="stat"><b>Galeri</b><span>Dokumentasi</span></div><div class="stat"><b>Tracer</b><span>Roadmap Data</span></div></div>
<div class="panel"><h2>Konsep Website</h2><div class="table-wrap"><table><thead><tr><th>Area</th><th>Fungsi</th><th>Output Publik</th></tr></thead><tbody><tr><td><b>Website Resmi</b></td><td>Profil organisasi, pengurus, kontak, struktur informasi resmi.</td><td>Publik melihat PSTI Jatim sebagai organisasi formal dan kredibel.</td></tr><tr><td><b>Blog / Media Center</b></td><td>Kelola artikel, berita resmi, pengumuman, opini, pembinaan, dan kompetisi.</td><td>Halaman Blog dengan kategori, pencarian, artikel unggulan, dan arsip.</td></tr><tr><td><b>Tracer Atlet</b></td><td>Ruang data atlet, asal daerah/klub, status, dan prestasi.</td><td>Public dapat melihat data atlet terstruktur.</td></tr><tr><td><b>Tracer Pelatih</b></td><td>Ruang data pelatih, lisensi, sertifikasi, dan pengalaman.</td><td>Public dapat melihat sebaran SDM pelatih.</td></tr><tr><td><b>Anggota</b></td><td>Pengurus, PSTI & Klub, serta Wasit.</td><td>Ekosistem organisasi terlihat jelas.</td></tr><tr><td><b>Kompetisi</b></td><td>Kejurda, Piala Gubernur, Agenda/Jadwal, dan klasemen.</td><td>Informasi event resmi mudah diakses.</td></tr></tbody></table></div></div>
<div class="panel"><h2>Cara Posting Artikel Blog</h2><ol><li>Buka menu <b>Berita</b> di sidebar admin.</li><li>Isi <b>Judul Artikel</b> dengan gaya formal dan informatif.</li><li>Pilih <b>Kategori Blog</b>: Berita Resmi, Pembinaan, Kompetisi, Atlet & Pelatih, Opini/Tulisan, atau Pengumuman.</li><li>Pilih status <b>Publish</b> jika langsung tampil, atau <b>Draft</b> untuk simpan sementara.</li><li>Isi tanggal publish, sumber, URL sumber jika ada, tags, dan isi artikel/ringkasan.</li><li>Upload gambar utama yang jelas dan profesional.</li><li>Klik <b>Simpan Artikel</b>, lalu cek halaman public <b>Blog</b>.</li></ol></div>
<div class="panel"><h2>Cara Kelola Agenda</h2><ol><li>Buka menu <b>Agenda</b>.</li><li>Isi nama kegiatan, tanggal/periode, lokasi, status, dan deskripsi.</li><li>Gunakan kategori kegiatan seperti kompetisi, pelatihan, rapat, seleksi, pelantikan, atau pembinaan.</li><li>Setelah agenda selesai, update status menjadi selesai dan tambahkan hasil/keterangan bila perlu.</li></ol></div>
<div class="panel"><h2>Cara Kelola Galeri</h2><ol><li>Buka menu <b>Galeri</b>.</li><li>Upload foto kegiatan dengan judul yang jelas.</li><li>Gunakan foto landscape bila memungkinkan.</li><li>Kelompokkan nama kegiatan di judul/caption agar mudah dicari.</li><li>Fase berikutnya galeri dapat ditingkatkan menjadi album per event.</li></ol></div>
<div class="panel"><h2>Standar Konten Premium</h2><ul><li>Gunakan bahasa Indonesia formal, singkat, dan jelas.</li><li>Judul artikel idealnya 6–14 kata.</li><li>Foto harus jelas, tidak blur, dan relevan dengan kegiatan.</li><li>Hindari upload dokumen sensitif ke halaman public.</li><li>Gunakan kategori blog secara konsisten agar arsip rapi.</li><li>Selalu cek public site setelah menyimpan konten.</li></ul></div>
<div class="panel"><h2>Roadmap Admin Berikutnya</h2><ol><li>CRUD <b>Tracer Atlet</b>: biodata, klub/daerah, prestasi, status.</li><li>CRUD <b>Tracer Pelatih</b>: lisensi, sertifikasi, pengalaman, klub binaan.</li><li>CRUD <b>PSTI & Klub</b>: profil klub, kab/kota, kontak, status aktif.</li><li>CRUD <b>Wasit</b>: lisensi, level, status aktif, riwayat penugasan.</li><li>Kompetisi: peserta, jadwal, hasil pertandingan, klasemen, bracket sederhana.</li><li>Galeri album per event dan dokumen resmi organisasi.</li></ol></div>

<div class="panel"><h2>Cara Pasang seperti Aplikasi</h2><ol><li><b>Android:</b> buka website PSTI Jatim di Chrome, tekan menu tiga titik, pilih <b>Install app</b> atau <b>Add to Home Screen</b>.</li><li><b>iPhone/iPad:</b> buka website di Safari, tekan tombol Share, pilih <b>Add to Home Screen</b>.</li><li>Setelah dipasang, ikon PSTI Jatim akan tampil di layar utama dan terbuka seperti aplikasi.</li><li>Versi ini adalah PWA. APK/AAB native bisa dibuat pada fase berikutnya dengan Capacitor atau TWA.</li></ol></div>
<div class="panel"><h2>Catatan Keamanan</h2><ul><li>Jangan bagikan akun admin ke publik.</li><li>Setelah final deploy, password awal wajib dirotasi.</li><li>Gunakan gambar dan teks yang memang boleh dipublikasikan.</li><li>File backup/arsip lama tetap harus diblokir dari akses publik.</li></ul></div>
<?php admin_footer(); ?>
